[general]
import = ["~/dotfiles/alacritty/.config/alacritty/carbonfox-theme.toml"]

[font]
size = 14
normal = { family = "DroidSansM Nerd Font Mono", style = "Regular"}

[window]
opacity = 0.85
blur = true
startup_mode = "Maximized"
