alias gst='git status'
alias gaa='git add --all'
alias gc='git commit'
alias gp='git push'
alias gpr='git pull --rebase'
alias gd='git diff'
alias gcb='git checkout branch'
alias gba='git branch --all'
alias grv='git remote --verbose'
alias gco='git checkout'
alias gl='git log --oneline --graph --decorate'
alias mine='cd ~/Documents/code/mine/'
alias theirs='cd ~/Documents/code/external/'
alias ..="cd .."
alias ~="cd ~"
alias c="clear"
alias grep="grep --color=auto"
alias pingg="ping google.com"
alias myip="curl ifconfig.me"
alias ports="ss -tulwn"
alias df="df -h"
alias du="du -h -c"
alias free="free -m"
alias path='echo -e ${PATH//:/\\n}'
alias h="history | grep"
alias j="jobs -l"
alias vi="nvim"
